AWSTemplateFormatVersion: 2010-09-09
Description: DNS RecordSet Infrastructure (Route53->CloudFront)
Parameters:
  AirCdnDomainName:
    Type: String
    Default: <AirCdnDomainName>
  AirCdnRedirectDomainName:
    Type: String
    Default: <AirCdnRedirectDomainName>
  DomainName:
    Type: String
    Default: <DomainName>
  DomainNameRedirect:
    Type: String
    Default: <DomainNameRedirect>
  Environment:
    Type: String
    Default: dev
    AllowedValues: [prod, dev, avery]
Resources:
  # Route53
  FireRecordARecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !ImportValue <GlobalHostedZoneId>
      Comment: !Sub "RecordSetGroup for ${DomainName}"
      RecordSets:
      # <DomainName>, <Environment>.<DomainName>
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !Ref AirCdnDomainName
          HostedZoneId: Z2FDTNDATAQYW2 #CloudFront's HostedZone
      # www.<DomainName>, <Environment>.www.<DomainName>
      - Name: !Ref DomainNameRedirect # redirect ://www. to ://
        Type: A
        AliasTarget:
          DNSName: !Ref AirCdnRedirectDomainName
          HostedZoneId: Z2FDTNDATAQYW2 #CloudFront's HostedZone
Outputs:
  FireRecordARecordSetGroup:
    Description: RecordSetGroup info
    Value: !Ref FireRecordARecordSetGroup